name: App Backend CI

on:
  push:
    branches:
      [production, staging, development]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: app_backend
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: app_backend
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: app_backend
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }} 
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        SECRET: "test_secret"
        ALGORITHM: "HS256"
      run: |
        pytest
