# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches:
      [production, staging, dev]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5'
          
      - name: Install dependencies
        working-directory: ./quack_app
        run: flutter pub get
        
      - name: Analyze Code
        working-directory: ./quack_app
        run: dart analyze
  
      - name: Run tests
        working-directory: ./quack_app
        run: flutter test  
