# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches:
      [production, staging, dev]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5'
          
      - name: Install dependencies
        working-directory: ./quack_app
        run: flutter pub get
        
      - name: Analyze Code
        working-directory: ./quack_app
        run: dart analyze
  
      - name: Run tests
        working-directory: ./quack_app
        run: flutter test --coverage
        
      - name: Install lcov
        working-directory: ./quack_app
        run: brew install lcov
        
      - name: Remove Misc. Code Coverage Files
        working-directory: ./quack_app
        run: lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.part.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' -o coverage/lcov.info
        
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./quack_app/coverage/lcov.info
          token: "${{ secrets.CODECOV_TOKEN }}"
