name: Move new issues into Product Backlog

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Cheese & Quackers Board
          column: Product Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
